<?php

return [
    'physics' => [
        ['question' => 'Does light travel faster in a vacuum than in air?', 'answer' => true],
        ['question' => 'Is sound faster than light?', 'answer' => false],
        ['question' => 'Can electricity flow through an open circuit?', 'answer' => false],
        ['question' => 'Is the unit of electric current measured in Watts?', 'answer' => false],
        ['question' => 'Do all objects fall at the same rate regardless of their mass?', 'answer' => true],
        ['question' => 'Is the moon a source of light?', 'answer' => false],
        ['question' => 'Are protons negatively charged particles?', 'answer' => false],
        ['question' => 'Can an object have potential energy without kinetic energy?', 'answer' => true],
        ['question' => 'Can a force change the direction of motion of an object without changing its speed?', 'answer' => true],
        ['question' => 'Is the nucleus of an atom positively charged?', 'answer' => true],
        ['question' => 'Are atoms the basic building blocks of matter?', 'answer' => true],
        ['question' => 'Is water a compound?', 'answer' => true],
        ['question' => 'Is gold a non-metal?', 'answer' => false],
        ['question' => 'Can chemical reactions convert matter into energy?', 'answer' => false],
        ['question' => 'Is hydrogen a noble gas?', 'answer' => false],
        ['question' => 'Are chemical bonds only possible between atoms of the same element?', 'answer' => false],
        ['question' => 'Is oxygen a gas at room temperature?', 'answer' => true],
        ['question' => 'Can matter be created or destroyed in a chemical reaction?', 'answer' => false],
        ['question' => 'Is the pH of a neutral solution 7?', 'answer' => true],
        ['question' => 'Does a catalyst increase the rate of a chemical reaction without being consumed?', 'answer' => true],
        ['question' => 'Does light exhibit wave-particle duality?', 'answer' => true],
        ['question' => 'Is the speed of light constant in all inertial frames of reference?', 'answer' => true],
        ['question' => 'Can an object have zero acceleration and still be moving?', 'answer' => false],
        ['question' => 'Is the concept of mass the same as weight?', 'answer' => false],
        ['question' => 'Does the force of gravity depend on the mass of an object?', 'answer' => true],
    ],
    'chemistry' => [
        ['question' => 'Are atoms the basic building blocks of matter?', 'answer' => true],
        ['question' => 'Is water a compound?', 'answer' => true],
        ['question' => 'Is gold a non-metal?', 'answer' => false],
        ['question' => 'Can chemical reactions convert matter into energy?', 'answer' => false],
        ['question' => 'Is hydrogen a noble gas?', 'answer' => false],
        ['question' => 'Are chemical bonds only possible between atoms of the same element?', 'answer' => false],
        ['question' => 'Is oxygen a gas at room temperature?', 'answer' => true],
        ['question' => 'Can matter be created or destroyed in a chemical reaction?', 'answer' => false],
        ['question' => 'Is the pH of a neutral solution 7?', 'answer' => true],
        ['question' => 'Does a catalyst increase the rate of a chemical reaction without being consumed?', 'answer' => true],
        ['question' => 'Does light exhibit wave-particle duality?', 'answer' => true],
        ['question' => 'Is the speed of light constant in all inertial frames of reference?', 'answer' => true],
        ['question' => 'Can an object have zero acceleration and still be moving?', 'answer' => false],
        ['question' => 'Is the concept of mass the same as weight?', 'answer' => false],
        ['question' => 'Does the force of gravity depend on the mass of an object?', 'answer' => true],
        ['question' => 'Is the density of a substance the same regardless of its size?', 'answer' => false],
        ['question' => 'Can an element have different isotopes?', 'answer' => true],
        ['question' => 'Is a chemical reaction a physical change?', 'answer' => false],
        ['question' => 'Are all acids corrosive?', 'answer' => false],
        ['question' => 'Is rusting an example of a chemical change?', 'answer' => true],
        ['question' => 'Are molecules of elements made up of multiple atoms?', 'answer' => true],
        ['question' => 'Is the valence shell of an atom always the outermost shell?', 'answer' => true],
        ['question' => 'Can a substance have more than one allotrope?', 'answer' => true],
        ['question' => 'Is a proton positively charged?', 'answer' => true],
        ['question' => 'Does the mass number represent the total number of protons and neutrons in an atom?', 'answer' => true],
    ]
];
